name: event_system
version: 1.2.0
author: Vitaliy Vostrikov <rasart.pro@gmail.com>
homepage: https://github.com/WhisperEngine/EventSystem.git
description: >
  EventSystem:
    Stream for decouple many objects;
    Simple subscription on object events;
    Work both, on client and server;
dev_dependencies:
  test: '^0.12.15+11'